### ISSUE TITLE
Yelp Data and Pinsage Implementation

### ISSUE THREAD

**Issue by jianing-sun** [xiangwang1223/neural_graph_collaborative_filtering#4]
Hi, thank you for your very impressed work. Just want to know if you can release the `.txt` file of your processed Yelp data as well.

Also, I'm curious about how you implement the `Pinsage` which is claimed from your paper. Is that the same with the `gcn` embedding in your code?

Thanks,

**Comment by xiangwang1223** [comment]
Hi, Thanks for your interest! Sorry for the late reply after a busy week.
1. You can use the released data to verify the experimental results. For Yelp2018 dataset, one version has been released at [our kdd work: KGAT](https://github.com/xiangwang1223/knowledge_graph_attention_network).

2. Pinsage implements the graph convolutional layer as that of Graphsage, rather than the `gcn` layer in our code. In case you want to use our framework to implement Pinsage, please refer to the source code via [our kdd work: KGAT](https://github.com/xiangwang1223/knowledge_graph_attention_network) and find the `graphsage` layer.

**Comment by jianing-sun** [comment]
Thanks a lot!
